import type { PreRequestRule, TestRule } from "@/types";

/**
 * Parses raw pre-request scripts back into PreRequestRule objects.
 */
export function parsePreRequestScript(script: string | undefined): PreRequestRule[] {
  if (!script) return [];

  const rules: PreRequestRule[] = [];
  const lines = script.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Optimized regex for quoted strings: (['"])((?:[^\1\\]|\\.)*)\1
    const setEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.set\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setEnvMatch) {
      rules.push({
        id: crypto.randomUUID(),
        type: "set_env_var",
        key: setEnvMatch[2],
        value: setEnvMatch[4],
      });
      continue;
    }

    const unsetEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.unset\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (unsetEnvMatch) {
      rules.push({ id: crypto.randomUUID(), type: "clear_env_var", key: unsetEnvMatch[2] });
      continue;
    }

    const setHeaderMatch = trimmed.match(
      /(?:pm|lz)\.request\.headers\.upsert\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setHeaderMatch) {
      rules.push({
        id: crypto.randomUUID(),
        type: "set_header",
        key: setHeaderMatch[2],
        value: setHeaderMatch[4],
      });
      continue;
    }

    const removeHeaderMatch = trimmed.match(
      /(?:pm|lz)\.request\.headers\.remove\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (removeHeaderMatch) {
      rules.push({ id: crypto.randomUUID(), type: "delete_header", key: removeHeaderMatch[2] });
    }
  }

  return rules;
}

/**
 * Parses raw test scripts back into TestRule objects.
 * This is best-effort and focuses on patterns generated by rule-compiler.ts.
 */
export function parseTestScript(script: string | undefined): TestRule[] {
  if (!script) return [];

  const rules: TestRule[] = [];

  // Regex to find lz.test blocks
  const testBlockRegex =
    /(?:pm|lz)\.test\s*\(\s*(['"])(.*?)\1\s*,\s*function\s*\(\s*\)\s*\{([\s\S]*?)\}\s*\);?/g;
  let match: RegExpExecArray | null = testBlockRegex.exec(script);

  while (match !== null) {
    const testBody = match[3].trim();

    // 1. Status Code
    // lz.expect(lz.response.status).to.equal(Number("200"));
    const statusMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.status\s*\)\.to\.(equal|not\.equal)\s*\(\s*Number\s*\(\s*(['"])(.*?)\2\s*\)\s*\);?/,
    );
    if (statusMatch) {
      rules.push({
        id: crypto.randomUUID(),
        target: "status_code",
        operator: statusMatch[1] === "equal" ? "equals" : "not_equals",
        value: statusMatch[3],
      });
    }

    // 2. Response Time
    // lz.expect(lz.response.time).to.be.below(Number("500"));
    const timeMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.time\s*\)\.to\.be\.(above|below)\s*\(\s*Number\s*\(\s*(['"])(.*?)\2\s*\)\s*\);?/,
    );
    if (timeMatch) {
      rules.push({
        id: crypto.randomUUID(),
        target: "response_time",
        operator: timeMatch[1] === "above" ? "greater_than" : "less_than",
        value: timeMatch[3],
      });
    }

    // 3. Headers
    // Header existence: lz.expect(lz.response.headers.has("Content-Type")).to.be.true;
    const headerExistsMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.headers\.has\s*\(\s*(['"])(.*?)\1\s*\)\s*\)\.to\.be\.(true|false);?/,
    );
    if (headerExistsMatch) {
      rules.push({
        id: crypto.randomUUID(),
        target: "header",
        property: headerExistsMatch[2],
        operator: headerExistsMatch[3] === "true" ? "exists" : "not_exists",
      });
    }

    // Header value: lz.expect(lz.response.headers.get("Content-Type")).to.equal("application/json");
    const headerValueMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.headers\.get\s*\(\s*(['"])(.*?)\1\s*\)\s*\)\.to\.(equal|include)\s*\(\s*(['"])(.*?)\4\s*\);?/,
    );
    if (headerValueMatch) {
      rules.push({
        id: crypto.randomUUID(),
        target: "header",
        property: headerValueMatch[2],
        operator: headerValueMatch[3] === "equal" ? "equals" : "contains",
        value: headerValueMatch[5],
      });
    }

    // 4. Body Contains
    // lz.expect(lz.response.text()).to.include("search");
    const bodyMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.text\(\)\s*\)\.to\.(equal|include|not\.include)\s*\(\s*(['"])(.*?)\2\s*\);?/,
    );
    if (bodyMatch) {
      const opMap: Record<string, TestRule["operator"]> = {
        equal: "equals",
        include: "contains",
        "not.include": "not_contains",
      };
      rules.push({
        id: crypto.randomUUID(),
        target: "body_contains",
        operator: opMap[bodyMatch[1]],
        value: bodyMatch[3],
      });
    }

    // 5. JSON Property
    // lz.expect(String(_.get(__jsonData, "data.id"))).to.equal(String("123"));
    const jsonPropMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(String|Number)\s*\(\s*_\.get\s*\(\s*__jsonData\s*,\s*(['"])(.*?)\2\s*\)\s*\)\s*\)\.to(\.not)?\.(equal|include|be\.above|be\.below)\s*\(\s*(String|Number)\s*\(\s*(['"])(.*?)\7\s*\)\s*\)\s*\);?/,
    );
    if (jsonPropMatch) {
      const isNot = !!jsonPropMatch[4];
      const op = jsonPropMatch[5];

      let operator: TestRule["operator"] = "equals";
      if (op === "equal") operator = isNot ? "not_equals" : "equals";
      else if (op === "include") operator = isNot ? "not_contains" : "contains";
      else if (op === "be.above") operator = "greater_than";
      else if (op === "be.below") operator = "less_than";

      rules.push({
        id: crypto.randomUUID(),
        target: "json_property",
        property: jsonPropMatch[3],
        operator: operator,
        value: jsonPropMatch[8],
      });
    }

    match = testBlockRegex.exec(script);
  }

  return rules;
}
