import type { PostRequestRule, PreRequestRule, TestRule } from "@/types";

/**
 * Parses raw pre-request scripts back into PreRequestRule objects.
 */
export function parsePreRequestScript(script: string | undefined): PreRequestRule[] {
  if (!script) return [];

  const rules: PreRequestRule[] = [];
  const lines = script.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Optimized regex for quoted strings: (['"])((?:[^\1\\]|\\.)*)\1
    const setEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.set\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setEnvMatch) {
      const key = setEnvMatch[2];
      const value = setEnvMatch[4];
      if (!key || value === undefined) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "set_env_var",
        key,
        value,
      });
      continue;
    }

    const unsetEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.unset\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (unsetEnvMatch) {
      const key = unsetEnvMatch[2];
      if (!key) continue;
      rules.push({ id: crypto.randomUUID(), type: "clear_env_var", key });
      continue;
    }

    const setHeaderMatch = trimmed.match(
      /(?:pm|lz)\.request\.headers\.upsert\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setHeaderMatch) {
      const key = setHeaderMatch[2];
      const value = setHeaderMatch[4];
      if (!key || value === undefined) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "set_header",
        key,
        value,
      });
      continue;
    }

    const removeHeaderMatch = trimmed.match(
      /(?:pm|lz)\.request\.headers\.remove\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (removeHeaderMatch) {
      const key = removeHeaderMatch[2];
      if (!key) continue;
      rules.push({ id: crypto.randomUUID(), type: "delete_header", key });
    }
  }

  return rules;
}

export function parsePostRequestScript(script: string | undefined): PostRequestRule[] {
  if (!script) return [];

  const rules: PostRequestRule[] = [];
  const lines = script.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const setEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.set\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setEnvMatch) {
      const key = setEnvMatch[2];
      const value = setEnvMatch[4];
      if (!key || value === undefined) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "set_env_var",
        key,
        value,
      });
      continue;
    }

    const unsetEnvMatch = trimmed.match(
      /(?:pm|lz)\.env\.unset\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (unsetEnvMatch) {
      const key = unsetEnvMatch[2];
      if (!key) continue;
      rules.push({ id: crypto.randomUUID(), type: "clear_env_var", key });
      continue;
    }

    const setHeaderMatch = trimmed.match(
      /(?:pm|lz)\.response\.headers\.(?:upsert|set)\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*,\s*(['"])((?:(?!\3)[^\\]|\\.)*)\3\s*\);?/,
    );
    if (setHeaderMatch) {
      const key = setHeaderMatch[2];
      const value = setHeaderMatch[4];
      if (!key || value === undefined) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "set_response_header",
        key,
        value,
      });
      continue;
    }

    const removeHeaderMatch = trimmed.match(
      /(?:pm|lz)\.response\.headers\.(?:remove|delete)\s*\(\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1\s*\);?/,
    );
    if (removeHeaderMatch) {
      const key = removeHeaderMatch[2];
      if (!key) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "delete_response_header",
        key,
      });
      continue;
    }

    const setBodyMatch = trimmed.match(
      /(?:pm|lz)\.response\.body\s*=\s*(['"])((?:(?!\1)[^\\]|\\.)*)\1;?/,
    );
    if (setBodyMatch) {
      const value = setBodyMatch[2];
      if (value === undefined) continue;
      rules.push({
        id: crypto.randomUUID(),
        type: "set_response_body",
        key: "",
        value,
      });
    }
  }

  return rules;
}

/**
 * Parses raw test scripts back into TestRule objects.
 * This is best-effort and focuses on patterns generated by rule-compiler.ts.
 */
export function parseTestScript(script: string | undefined): TestRule[] {
  if (!script) return [];

  const rules: TestRule[] = [];

  // Regex to find lz.test blocks
  const testBlockRegex =
    /(?:pm|lz)\.test\s*\(\s*(['"])(.*?)\1\s*,\s*function\s*\(\s*\)\s*\{([\s\S]*?)\}\s*\);?/g;
  let match: RegExpExecArray | null = testBlockRegex.exec(script);

  while (match !== null) {
    const testBody = match[3]?.trim();
    if (!testBody) {
      match = testBlockRegex.exec(script);
      continue;
    }

    // 1. Status Code
    // lz.expect(lz.response.status).to.equal(Number("200"));
    const statusMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.status\s*\)\.to\.(equal|not\.equal)\s*\(\s*Number\s*\(\s*(['"])(.*?)\2\s*\)\s*\);?/,
    );
    if (statusMatch) {
      const value = statusMatch[3];
      if (value === undefined) {
        match = testBlockRegex.exec(script);
        continue;
      }
      rules.push({
        id: crypto.randomUUID(),
        target: "status_code",
        operator: statusMatch[1] === "equal" ? "equals" : "not_equals",
        value,
      });
    }

    // 2. Response Time
    // lz.expect(lz.response.time).to.be.below(Number("500"));
    const timeMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.time\s*\)\.to\.be\.(above|below)\s*\(\s*Number\s*\(\s*(['"])(.*?)\2\s*\)\s*\);?/,
    );
    if (timeMatch) {
      const value = timeMatch[3];
      if (value === undefined) {
        match = testBlockRegex.exec(script);
        continue;
      }
      rules.push({
        id: crypto.randomUUID(),
        target: "response_time",
        operator: timeMatch[1] === "above" ? "greater_than" : "less_than",
        value,
      });
    }

    // 3. Headers
    // Header existence: lz.expect(lz.response.headers.has("Content-Type")).to.be.true;
    const headerExistsMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.headers\.has\s*\(\s*(['"])(.*?)\1\s*\)\s*\)\.to\.be\.(true|false);?/,
    );
    if (headerExistsMatch) {
      const property = headerExistsMatch[2];
      if (!property) {
        match = testBlockRegex.exec(script);
        continue;
      }
      rules.push({
        id: crypto.randomUUID(),
        target: "header",
        property,
        operator: headerExistsMatch[3] === "true" ? "exists" : "not_exists",
      });
    }

    // Header value: lz.expect(lz.response.headers.get("Content-Type")).to.equal("application/json");
    const headerValueMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.headers\.get\s*\(\s*(['"])(.*?)\1\s*\)\s*\)\.to\.(equal|include)\s*\(\s*(['"])(.*?)\4\s*\);?/,
    );
    if (headerValueMatch) {
      const property = headerValueMatch[2];
      const value = headerValueMatch[5];
      if (!property || value === undefined) {
        match = testBlockRegex.exec(script);
        continue;
      }
      rules.push({
        id: crypto.randomUUID(),
        target: "header",
        property,
        operator: headerValueMatch[3] === "equal" ? "equals" : "contains",
        value,
      });
    }

    // 4. Body Contains
    // lz.expect(lz.response.text()).to.include("search");
    const bodyMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(?:pm|lz)\.response\.text\(\)\s*\)\.to\.(equal|include|not\.include)\s*\(\s*(['"])(.*?)\2\s*\);?/,
    );
    if (bodyMatch) {
      const opMap: Record<string, TestRule["operator"]> = {
        equal: "equals",
        include: "contains",
        "not.include": "not_contains",
      };
      const opKey = bodyMatch[1];
      const operator = opKey ? opMap[opKey] : undefined;
      const value = bodyMatch[3];
      if (!operator || value === undefined) {
        match = testBlockRegex.exec(script);
        continue;
      }
      rules.push({
        id: crypto.randomUUID(),
        target: "body_contains",
        operator,
        value,
      });
    }

    // 5. JSON Property
    // lz.expect(String(_.get(__jsonData, "data.id"))).to.equal(String("123"));
    const jsonPropMatch = testBody.match(
      /(?:pm|lz)\.expect\s*\(\s*(String|Number)\s*\(\s*_\.get\s*\(\s*__jsonData\s*,\s*(['"])(.*?)\2\s*\)\s*\)\s*\)\.to(\.not)?\.(equal|include|be\.above|be\.below)\s*\(\s*(String|Number)\s*\(\s*(['"])(.*?)\7\s*\)\s*\)\s*\);?/,
    );
    if (jsonPropMatch) {
      const isNot = !!jsonPropMatch[4];
      const op = jsonPropMatch[5];

      let operator: TestRule["operator"] = "equals";
      if (op === "equal") operator = isNot ? "not_equals" : "equals";
      else if (op === "include") operator = isNot ? "not_contains" : "contains";
      else if (op === "be.above") operator = "greater_than";
      else if (op === "be.below") operator = "less_than";

      const property = jsonPropMatch[3];
      const value = jsonPropMatch[8];
      if (!property || value === undefined) {
        match = testBlockRegex.exec(script);
        continue;
      }

      rules.push({
        id: crypto.randomUUID(),
        target: "json_property",
        property,
        operator,
        value,
      });
    }

    match = testBlockRegex.exec(script);
  }

  return rules;
}
